<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.506">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sangho Lee">
<meta name="dcterms.date" content="2024-05-01">

<title>hw2_questions_2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="hw2_questions_2_files/libs/clipboard/clipboard.min.js"></script>
<script src="hw2_questions_2_files/libs/quarto-html/quarto.js"></script>
<script src="hw2_questions_2_files/libs/quarto-html/popper.min.js"></script>
<script src="hw2_questions_2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="hw2_questions_2_files/libs/quarto-html/anchor.min.js"></script>
<link href="hw2_questions_2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="hw2_questions_2_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="hw2_questions_2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="hw2_questions_2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="hw2_questions_2_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sangho Lee </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 1, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="airbnb-case-study" class="level2">
<h2 class="anchored" data-anchor-id="airbnb-case-study">AirBnB Case Study</h2>
<section id="introduction" class="level3">
<h3 class="anchored" data-anchor-id="introduction">Introduction</h3>
<p>AirBnB is a popular platform for booking short-term rentals. In March 2017, students Annika Awad, Evan Lebo, and Anna Linden scraped of 40,000 Airbnb listings from New York City.</p>
<p>In the dynamic market of short-term rental platforms, understanding the pricing strategies and customer preferences is crucial for maximizing profitability and enhancing service delivery. This analysis delves into the Airbnb dataset to explore the distribution of prices across different room types—Private rooms, Entire homes/apartments, and Shared rooms. By examining the variability in pricing and the density of outliers, we aim to discern which room type not only attracts the most customers but also offers the most lucrative business model for hosts.</p>
<p>The goal is to identify the best business model by analyzing how room type influences pricing strategies and guest feedback. This involves assessing the median prices, the spread of prices, and the presence of price outliers within each category. Such insights will be instrumental for Airbnb hosts to optimize their offerings and for the platform to advise new hosts on the most profitable room types to list.</p>
<p>The data include the following variables:</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Variable Definitions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<pre><code>- `id` = unique ID number for each unit
- `last_scraped` = date when information scraped
- `host_since` = date when host first listed the unit on Airbnb
- `days` = `last_scraped` - `host_since` = number of days the unit has been listed
- `room_type` = Entire home/apt., Private room, or Shared room
- `bathrooms` = number of bathrooms
- `bedrooms` = number of bedrooms
- `price` = price per night (dollars)
- `number_of_reviews` = number of reviews for the unit on Airbnb
- `review_scores_cleanliness` = a cleanliness score from reviews (1-10)
- `review_scores_location` = a "quality of location" score from reviews (1-10)
- `review_scores_value` = a "quality of value" score from reviews (1-10)
- `instant_bookable` = "t" if instantly bookable, "f" if not</code></pre>
</div>
</div>
</div>
</section>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<section id="i-will-begin-by-acquiring-and-examining-the-dataset-that-is-available.-i-will-proceed-to-load-and-inspect-this-data-using-both-python-and-r-equipping-me-to-perform-various-tasks-as-necessary." class="level4">
<h4 class="anchored" data-anchor-id="i-will-begin-by-acquiring-and-examining-the-dataset-that-is-available.-i-will-proceed-to-load-and-inspect-this-data-using-both-python-and-r-equipping-me-to-perform-various-tasks-as-necessary.">I will begin by acquiring and examining the dataset that is available. I will proceed to load and inspect this data using both Python and R, equipping me to perform various tasks as necessary.</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(magrittr)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reticulate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>airbnb <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"airbnb.csv"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>airbnb <span class="sc">%&gt;%</span> </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">10</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 1%">
<col style="width: 2%">
<col style="width: 2%">
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 8%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 3%">
<col style="width: 9%">
<col style="width: 14%">
<col style="width: 12%">
<col style="width: 10%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">X</th>
<th style="text-align: right;">id</th>
<th style="text-align: right;">days</th>
<th style="text-align: left;">last_scraped</th>
<th style="text-align: left;">host_since</th>
<th style="text-align: left;">room_type</th>
<th style="text-align: right;">bathrooms</th>
<th style="text-align: right;">bedrooms</th>
<th style="text-align: right;">price</th>
<th style="text-align: right;">number_of_reviews</th>
<th style="text-align: right;">review_scores_cleanliness</th>
<th style="text-align: right;">review_scores_location</th>
<th style="text-align: right;">review_scores_value</th>
<th style="text-align: left;">instant_bookable</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">2515</td>
<td style="text-align: right;">3130</td>
<td style="text-align: left;">4/2/2017</td>
<td style="text-align: left;">9/6/2008</td>
<td style="text-align: left;">Private room</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">59</td>
<td style="text-align: right;">150</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">f</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">2595</td>
<td style="text-align: right;">3127</td>
<td style="text-align: left;">4/2/2017</td>
<td style="text-align: left;">9/9/2008</td>
<td style="text-align: left;">Entire home/apt</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">230</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">f</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">3647</td>
<td style="text-align: right;">3050</td>
<td style="text-align: left;">4/2/2017</td>
<td style="text-align: left;">11/25/2008</td>
<td style="text-align: left;">Private room</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">150</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">f</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">3831</td>
<td style="text-align: right;">3038</td>
<td style="text-align: left;">4/2/2017</td>
<td style="text-align: left;">12/7/2008</td>
<td style="text-align: left;">Entire home/apt</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">89</td>
<td style="text-align: right;">116</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">f</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">4611</td>
<td style="text-align: right;">3012</td>
<td style="text-align: left;">4/2/2017</td>
<td style="text-align: left;">1/2/2009</td>
<td style="text-align: left;">Private room</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">39</td>
<td style="text-align: right;">93</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">t</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">5099</td>
<td style="text-align: right;">2981</td>
<td style="text-align: left;">4/2/2017</td>
<td style="text-align: left;">2/2/2009</td>
<td style="text-align: left;">Entire home/apt</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">212</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">f</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">5107</td>
<td style="text-align: right;">2981</td>
<td style="text-align: left;">4/2/2017</td>
<td style="text-align: left;">2/2/2009</td>
<td style="text-align: left;">Entire home/apt</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">250</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">f</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">5121</td>
<td style="text-align: right;">2980</td>
<td style="text-align: left;">4/2/2017</td>
<td style="text-align: left;">2/3/2009</td>
<td style="text-align: left;">Private room</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">f</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">5172</td>
<td style="text-align: right;">2980</td>
<td style="text-align: left;">4/2/2017</td>
<td style="text-align: left;">2/3/2009</td>
<td style="text-align: left;">Entire home/apt</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">129</td>
<td style="text-align: right;">53</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">f</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">5178</td>
<td style="text-align: right;">2952</td>
<td style="text-align: left;">4/2/2017</td>
<td style="text-align: left;">3/3/2009</td>
<td style="text-align: left;">Private room</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">79</td>
<td style="text-align: right;">329</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">f</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pyrsm <span class="im">as</span> rsm</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>airbnb <span class="op">=</span> pd.read_csv(<span class="st">"airbnb.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br></p>
<p>Next, I will focus on analyzing the number of reviews across different room types using box plots. This approach will allow me to compare the spread and central tendency of review counts, providing insights into the variability and typical values within each category of accommodation. By examining these plots, I will assess patterns such as outliers, skewness, and the overall distribution range among Entire homes/apartments, Private rooms, and Shared rooms.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>price_upper_limit <span class="op">=</span> airbnb[<span class="st">'price'</span>].quantile(<span class="fl">0.95</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">16</span>, <span class="dv">12</span>))</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>sns.boxplot(data<span class="op">=</span>airbnb, x<span class="op">=</span><span class="st">'room_type'</span>, y<span class="op">=</span><span class="st">'price'</span>, palette<span class="op">=</span><span class="st">'Set2'</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Price Distribution by Room Type'</span>, fontsize<span class="op">=</span><span class="dv">34</span>)  </span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Room Type'</span>, fontsize<span class="op">=</span><span class="dv">30</span>)  </span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Price Per Night'</span>, fontsize<span class="op">=</span><span class="dv">30</span>)  </span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>plt.ylim(<span class="dv">0</span>, price_upper_limit)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(0.0, 350.0)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>plt.xticks(fontsize<span class="op">=</span><span class="dv">26</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>([0, 1, 2], [Text(0, 0, 'Private room'), Text(1, 0, 'Entire home/apt'), Text(2, 0, 'Shared room')])</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>plt.yticks(fontsize<span class="op">=</span><span class="dv">26</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(array([  0.,  50., 100., 150., 200., 250., 300., 350.]), [Text(0, 0.0, '0'), Text(0, 50.0, '50'), Text(0, 100.0, '100'), Text(0, 150.0, '150'), Text(0, 200.0, '200'), Text(0, 250.0, '250'), Text(0, 300.0, '300'), Text(0, 350.0, '350')])</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="hw2_questions_2_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="1536"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="interpretation-of-the-box-plot" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-of-the-box-plot">Interpretation of the box plot</h3>
<section id="private-room" class="level4">
<h4 class="anchored" data-anchor-id="private-room">Private Room:</h4>
<ul>
<li>The box plot shows a relatively lower price range compared to the other room types, with the majority of prices clustered around the lower quartile.</li>
<li>The median price appears to be around $50, indicating that half of the private rooms are priced below this amount.</li>
<li>There are several outliers above the upper whisker, suggesting that some private rooms are priced significantly higher than typical listings.</li>
</ul>
</section>
<section id="entire-homeapt" class="level4">
<h4 class="anchored" data-anchor-id="entire-homeapt">Entire Home/Apt:</h4>
<ul>
<li>This category exhibits the highest median price, around $150, reflecting its status as a more premium option.</li>
<li>The interquartile range (IQR) is wider, indicating a larger variation in prices for entire homes or apartments compared to private rooms.</li>
<li>There are many outliers indicating that a significant number of entire homes/apartments are priced much higher than the upper quartile.</li>
</ul>
</section>
<section id="shared-room" class="level4">
<h4 class="anchored" data-anchor-id="shared-room">Shared Room:</h4>
<ul>
<li>Shared rooms show the lowest median price, around $35, which is expected given the shared nature of the accommodation.</li>
<li>The box for shared rooms is relatively compact, indicating less variation in price compared to the other room types.</li>
<li>There are a few outliers, but not as extreme as in the case of private rooms.</li>
</ul>
</section>
<section id="overall-insights" class="level4">
<h4 class="anchored" data-anchor-id="overall-insights">Overall Insights:</h4>
<ul>
<li>The price distribution indicates that entire homes or apartments are generally the most expensive type of accommodation on Airbnb, followed by private rooms, and then shared rooms.</li>
<li>The presence of outliers in each category, particularly in entire homes and private rooms, suggests that there are premium offerings in these categories that significantly exceed typical prices.</li>
<li>The variability in prices for entire homes/apartments is greater, potentially due to differences in size, location, or additional amenities offered. This analysis can help Airbnb hosts and users understand typical pricing structures and adjust their expectations or pricing strategies accordingly.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">20</span>, <span class="dv">18</span>))</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>sns.scatterplot(x<span class="op">=</span><span class="st">'price'</span>, y<span class="op">=</span><span class="st">'review_scores_value'</span>, data<span class="op">=</span>airbnb)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Price vs. Review Scores Value'</span>, fontsize<span class="op">=</span><span class="dv">34</span>)  </span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Price'</span>, fontsize<span class="op">=</span><span class="dv">30</span>) </span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Review Score Value'</span>, fontsize<span class="op">=</span><span class="dv">30</span>)  </span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>plt.xticks(fontsize<span class="op">=</span><span class="dv">26</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(array([-2000.,     0.,  2000.,  4000.,  6000.,  8000., 10000., 12000.]), [Text(-2000.0, 0, '−2000'), Text(0.0, 0, '0'), Text(2000.0, 0, '2000'), Text(4000.0, 0, '4000'), Text(6000.0, 0, '6000'), Text(8000.0, 0, '8000'), Text(10000.0, 0, '10000'), Text(12000.0, 0, '12000')])</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>plt.yticks(fontsize<span class="op">=</span><span class="dv">26</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]), [Text(0, 1.0, '1'), Text(0, 2.0, '2'), Text(0, 3.0, '3'), Text(0, 4.0, '4'), Text(0, 5.0, '5'), Text(0, 6.0, '6'), Text(0, 7.0, '7'), Text(0, 8.0, '8'), Text(0, 9.0, '9'), Text(0, 10.0, '10'), Text(0, 11.0, '11')])</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="hw2_questions_2_files/figure-html/unnamed-chunk-6-3.png" class="img-fluid figure-img" width="1920"></p>
</figure>
</div>
</div>
</div>
<p>This scatter plot visualizes the relationship between the price of Airbnb listings and their review scores for value. Here’s an interpretation based on the plot:</p>
<ul>
<li><p>Concentration of Data Points: The majority of listings are priced below $2000, with most review scores clustered around the higher end (8 to 10). This suggests that more reasonably priced listings tend to have higher value ratings from guests.</p></li>
<li><p>High-Price Listings: There are a few listings priced above $2000, reaching up to $10000. Interestingly, these high-priced listings still maintain relatively high review scores, mostly around 8 to 9. However, it’s noteworthy that no scores below 7 are visible, indicating that guests might still perceive these high-priced listings as offering good value, likely due to luxury or unique features.</p></li>
<li><p>Plateau of Review Scores: The review scores predominantly range from 8 to 10 across all price ranges, suggesting that most guests feel they receive good value for what they pay, independent of the listing price. This could indicate a consistent level of satisfaction with the perceived value among Airbnb users.</p></li>
<li><p>Lower Scores at Mid-Range Prices: A few listings in the mid-price range (around $2000 to $4000) have lower review scores (as low as 3), which could suggest that guests might have higher expectations that are not met when spending more. It appears these are outliers, as most other listings in similar price ranges maintain higher scores.</p></li>
<li><p>Low-Price, Low-Score Trend: Interestingly, the plot also reveals a trend where the lowest-priced listings (below around $50) sometimes receive lower value scores, suggesting that extremely low prices might be associated with subpar accommodations or services. This could indicate that while most low to moderately priced listings offer good value, there is a threshold below which the quality drops significantly, impacting guest satisfaction.</p></li>
<li><p>Overall, the plot shows that while price varies widely among Airbnb listings, the review scores for value remain high across the board, with notable exceptions at both mid-range and very low prices. This suggests that both under-delivering at mid-range prices and potential quality issues at extremely low prices can be detrimental to guest perceptions of value. This indicates that price alone may not be a deterrent to receiving high value scores, provided the offerings align well with guest expectations.</p></li>
</ul>
<p><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">8</span>))</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>sns.pointplot(x<span class="op">=</span><span class="st">'room_type'</span>, y<span class="op">=</span><span class="st">'review_scores_value'</span>, data<span class="op">=</span>airbnb, join<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Room Type vs. Review Scores Value'</span>, fontsize<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Room Type'</span>, fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Review Score Value'</span>, fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>plt.xticks(fontsize<span class="op">=</span><span class="dv">14</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>([0, 1, 2], [Text(0, 0, 'Private room'), Text(1, 0, 'Entire home/apt'), Text(2, 0, 'Shared room')])</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>plt.yticks(fontsize<span class="op">=</span><span class="dv">14</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(array([9.18, 9.2 , 9.22, 9.24, 9.26, 9.28, 9.3 , 9.32, 9.34, 9.36, 9.38]), [Text(0, 9.18, '9.18'), Text(0, 9.2, '9.20'), Text(0, 9.219999999999999, '9.22'), Text(0, 9.24, '9.24'), Text(0, 9.26, '9.26'), Text(0, 9.28, '9.28'), Text(0, 9.299999999999999, '9.30'), Text(0, 9.32, '9.32'), Text(0, 9.34, '9.34'), Text(0, 9.36, '9.36'), Text(0, 9.379999999999999, '9.38')])</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="hw2_questions_2_files/figure-html/unnamed-chunk-7-5.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<section id="general-observations" class="level5">
<h5 class="anchored" data-anchor-id="general-observations">General Observations:</h5>
<ul>
<li>The plot displays review scores for three different room types: Private room, Entire home/apt, and Shared room.</li>
<li>Each room type is represented by a point indicating the median review score value, along with vertical lines showing the range of the scores.</li>
</ul>
</section>
<section id="private-room-1" class="level5">
<h5 class="anchored" data-anchor-id="private-room-1">Private Room:</h5>
<ul>
<li>Median Score: Around 9.30.</li>
<li>Range: Narrow, indicating consistent review scores that cluster closely around the median. This suggests that guests have relatively uniform expectations and experiences in private rooms.</li>
</ul>
</section>
<section id="entire-homeapt-1" class="level5">
<h5 class="anchored" data-anchor-id="entire-homeapt-1">Entire Home/Apt:</h5>
<ul>
<li>Median Score: Slightly higher than Private rooms, roughly around 9.35.</li>
<li>Range: Also narrow, similar to Private rooms, which indicates consistent satisfaction among guests. The slightly higher median score might suggest that guests typically enjoy slightly better experiences or perceive better value in entire homes or apartments compared to private rooms.</li>
</ul>
</section>
<section id="shared-room-1" class="level5">
<h5 class="anchored" data-anchor-id="shared-room-1">Shared Room:</h5>
<ul>
<li>Median Score: Significantly lower, around 9.27.</li>
<li>Range: Much wider than the other two categories, extending from about 9.20 to 9.34. This indicates a high variability in guest experiences and satisfaction levels in shared rooms. The lower median score and wider range reflect the mixed reviews that shared rooms might receive, possibly due to the varying comfort levels and privacy standards among different guests.</li>
</ul>
</section>
<section id="implications" class="level5">
<h5 class="anchored" data-anchor-id="implications">Implications:</h5>
<ul>
<li>Consistency in Private Rooms and Entire Homes: The narrow score ranges for Private rooms and Entire homes/apt suggest that these options are perceived consistently by guests, which could be beneficial for hosts focusing on these types of listings.</li>
<li>Variability in Shared Rooms: The broad range for Shared rooms points to inconsistent experiences, which could be a concern for hosts. They might need to manage expectations more carefully or improve aspects of the shared living arrangements to enhance satisfaction.</li>
</ul>
</section>
</section>
</section>
</section>
<section id="synopsis-of-the-exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="synopsis-of-the-exploratory-data-analysis">Synopsis of the Exploratory Data Analysis</h2>
<section id="overview" class="level4">
<h4 class="anchored" data-anchor-id="overview">Overview</h4>
<ul>
<li>The first plot indicates the relationship between listing prices and the review scores assigned by guests, while the second plot focuses on how different room types—Private room, Entire home/apt, and Shared room—score on reviews.</li>
</ul>
</section>
<section id="analysis-of-entire-homes-under-2000" class="level4">
<h4 class="anchored" data-anchor-id="analysis-of-entire-homes-under-2000">Analysis of Entire Homes under $2000</h4>
<ul>
<li>Review Scores Across Prices: From the “Price vs.&nbsp;Review Scores Value” scatter plot, it appears that listings priced under $2000, particularly those categorized as Entire homes/apartments, generally receive high review scores. This suggests that guests perceive these listings as offering good value, likely due to a combination of affordability, privacy, and amenities provided.</li>
<li>Concentration of High Scores: Most of the high review scores (around 9 to 10) cluster at prices below $2000. This indicates that Entire homes/apartments priced within this range are particularly well-received, providing an optimal balance between cost and guest satisfaction.</li>
</ul>
</section>
<section id="synthesis-and-implications" class="level4">
<h4 class="anchored" data-anchor-id="synthesis-and-implications">Synthesis and Implications</h4>
<ul>
<li>Optimal Pricing Strategy for Entire Homes: The data suggests that Entire homes/apartments priced below $2000 not only receive high review scores but also do so consistently. This price point is likely seen as offering the best value for money among the various types of accommodations available on Airbnb.</li>
<li>Marketing Strategy: For Airbnb hosts, focusing on Entire homes/apartments within this price range could be a strategic move to attract guests seeking both quality and value. Marketing efforts could highlight the benefits of choosing an Entire home/apt, such as greater space and privacy, which are evidently valued by guests as reflected in their reviews.</li>
</ul>
</section>
<section id="revenue-management" class="level4">
<h4 class="anchored" data-anchor-id="revenue-management">Revenue Management</h4>
<ul>
<li>Pricing Entire homes/apartments competitively, yet within the optimal range under $2000, could maximize occupancy rates while maintaining high guest satisfaction. This approach could also mitigate the risk of negative reviews that more commonly affect higher-priced listings or those offering less privacy, like Shared rooms.</li>
<li>In conclusion, Entire homes/apartments priced below $2000 represent a sweet spot on Airbnb, yielding high review scores and indicating high guest satisfaction. Hosts might consider this pricing strategy to enhance both guest experience and competitive edge in the Airbnb market. This strategy not only caters to guest preferences for value but also aligns with the broader objective of maximizing positive reviews, which are crucial for sustained success on the platform.</li>
</ul>
<p><br><br></p>
</section>
</section>
<section id="estimation-of-simple-poisson-model" class="level2">
<h2 class="anchored" data-anchor-id="estimation-of-simple-poisson-model">Estimation of Simple Poisson Model</h2>
<p>Since our outcome variable of interest, the number of reviews per listing, consists of small integer values and represents counts over time, we can use a Poisson distribution to model it. This is appropriate because review counts are discrete, non-negative, and can be assumed to occur independently across different listings. I’ll start by estimating a simple Poisson model via Maximum Likelihood to understand the average rate at which reviews are given to listings.</p>
<p>Now, I’ll write the code for the likelihood or log-likelihood function of the Poisson model. This function is crucial for analyzing count data effectively, which is integral to our project’s statistical modeling. By understanding and implementing this function, I’ll be better equipped to handle data that inherently follows a Poisson distribution, providing insights into how often guests review Airbnb listings.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>poisson_loglikelihood <span class="ot">&lt;-</span> <span class="cf">function</span>(lambda, y) {</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  n <span class="ot">&lt;-</span> <span class="fu">length</span>(y) </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  likelihood <span class="ot">&lt;-</span> <span class="sc">-</span>n <span class="sc">*</span> lambda <span class="sc">+</span> <span class="fu">sum</span>(y <span class="sc">*</span> <span class="fu">log</span>(lambda)) <span class="sc">-</span> <span class="fu">sum</span>(<span class="fu">lgamma</span>(y <span class="sc">+</span> <span class="dv">1</span>))</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(likelihood)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="plotting-log-likelihood" class="level4">
<h4 class="anchored" data-anchor-id="plotting-log-likelihood">Plotting Log-Likelihood</h4>
<p>After defining the log-likelihood function for our Poisson model, the next step is to use this function to plot how the log-likelihood changes with different values of the parameter lambda. This parameter represents the average number of reviews per listing, and understanding its effect is crucial for our model. I’ll vary lambda over a range and use the observed number of reviews as the input value for y. This graphical representation will assist in visualizing how different lambda values influence the likelihood, aiding in the selection of the most appropriate lambda for our analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> airbnb<span class="sc">$</span>number_of_reviews</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate a sequence of lambda values</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>lambda_values <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">0.1</span>, <span class="dv">10</span>, <span class="at">by =</span> <span class="fl">0.1</span>)</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute log-likelihood for each lambda using the poisson_loglikelihood function defined earlier</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>log_likelihoods <span class="ot">&lt;-</span> <span class="fu">sapply</span>(lambda_values, <span class="cf">function</span>(l) <span class="fu">poisson_loglikelihood</span>(l, y))</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting the log-likelihood against lambda</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>data_to_plot <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">lambda =</span> lambda_values, <span class="at">log_likelihood =</span> log_likelihoods)</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data_to_plot, <span class="fu">aes</span>(<span class="at">x =</span> lambda, <span class="at">y =</span> log_likelihood)) <span class="sc">+</span></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Log-Likelihood of Poisson Model for Airbnb Reviews"</span>,</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Lambda (λ)"</span>,</span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Log-Likelihood"</span>) <span class="sc">+</span></span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="hw2_questions_2_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="plot-interpretation" class="level4">
<h4 class="anchored" data-anchor-id="plot-interpretation">Plot Interpretation</h4>
<ul>
<li><p>Shape of the Curve: The curve is unimodal, showing a clear peak which indicates the maximum log-likelihood. This peak represents the most probable value of lambda (λ) that fits the observed review count data in terms of likelihood maximization.</p></li>
<li><p>Maximum Likelihood Estimate (MLE): The value of λ at the peak of the curve is the Maximum Likelihood Estimate for the Poisson model’s rate parameter. This is the point where the derivative of the log-likelihood function with respect to λ is zero, indicating no further increase in likelihood is possible by increasing or decreasing λ.</p></li>
<li><p>Interpretation of λ: In the context of the Poisson distribution for this Airbnb data, λ represents the average number of reviews per listing. Observing the plot, the MLE of λ appears to be around 2.5, though the exact value can be more accurately determined using optimization techniques such as the optim() function in R or by directly examining the computed log-likelihood values.</p></li>
<li><p>Goodness of Fit: The shape of the curve around the peak provides insights into the precision of the estimate. A sharper, narrower peak suggests a more precise estimate of λ, indicating a clear optimization signal for the model. The relatively steep rise and decline around the peak suggest that the model is sensitive to changes in λ around the MLE, enhancing confidence in the lambda estimate’s precision.</p></li>
<li><p>Usefulness: This log-likelihood plot is highly useful for optimization because it confirms the existence of a maximum likelihood point. Such a plot aids in visual verification that the model parameters can indeed be optimized to find a best-fit λ, aligning with the purpose of the optim() function which seeks to locate this point of maximum likelihood.</p></li>
</ul>
<p><br></p>
</section>
<section id="optimization-of-the-poisson-model" class="level4">
<h4 class="anchored" data-anchor-id="optimization-of-the-poisson-model">Optimization of the Poisson Model</h4>
<p>I will now proceed to find the maximum likelihood estimate (MLE) by optimizing the likelihood function for the number of reviews on Airbnb listings. I’ll use the optim() function in R to perform this optimization. This step will help identify the parameter values that make the observed data most probable under the assumed Poisson distribution model, ensuring the best fit for our statistical analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the negative log-likelihood function for the Poisson distribution</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>neg_log_likelihood_poisson <span class="ot">&lt;-</span> <span class="cf">function</span>(lambda, y) {</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (lambda <span class="sc">&lt;=</span> <span class="dv">0</span>) {</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="cn">Inf</span>)  </span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  n <span class="ot">&lt;-</span> <span class="fu">length</span>(y)</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  likelihood <span class="ot">&lt;-</span> n <span class="sc">*</span> lambda <span class="sc">-</span> <span class="fu">sum</span>(y <span class="sc">*</span> <span class="fu">log</span>(lambda)) <span class="sc">+</span> <span class="fu">sum</span>(<span class="fu">lgamma</span>(y <span class="sc">+</span> <span class="dv">1</span>))</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(likelihood)</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> airbnb<span class="sc">$</span>number_of_reviews  </span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a><span class="co"># The starting value for lambda is chosen as the mean of y, which is a reasonable initial guess</span></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">optim</span>(<span class="at">par =</span> <span class="fu">mean</span>(y), <span class="at">fn =</span> neg_log_likelihood_poisson, <span class="at">y =</span> y, <span class="at">method =</span> <span class="st">"BFGS"</span>)</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a><span class="co"># The MLE of lambda</span></span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>lambda_mle <span class="ot">&lt;-</span> result<span class="sc">$</span>par</span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(lambda_mle)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 15.90443</code></pre>
</div>
</div>
</section>
<section id="interpreting-the-maximum-likelihood-estimate-mle-for-airbnb-reviews" class="level4">
<h4 class="anchored" data-anchor-id="interpreting-the-maximum-likelihood-estimate-mle-for-airbnb-reviews">Interpreting the Maximum Likelihood Estimate (MLE) for Airbnb Reviews</h4>
<p>The output of 15.90443 from the optim() function represents the maximum likelihood estimate (MLE) for the parameter λ of the Poisson distribution, which models the number of reviews received by each listing on Airbnb.</p>
<ul>
<li><p>Mean Rate (λ): The MLE λ of 15.90443 suggests that, under the Poisson model, the average number of reviews received per listing over the observed period is approximately 15.9. This indicates a relatively high level of guest interaction, assuming the data spans a typical listing lifecycle.</p></li>
<li><p>Model Assumption: This estimation is based on the assumption that the number of reviews follows a Poisson distribution, where each review count is independent of others and occurs with a constant mean rate. This is a standard assumption in modeling count data, which assumes that events (in this case, reviews) occur randomly and independently across the observed space (Airbnb listings).</p></li>
<li><p>Data Fit: The estimated λ provides the value that makes the observed data most probable under the Poisson model, indicating that it offers the best fit to the data according to the likelihood principle. This fit is critical for ensuring that the model accurately reflects the process generating the data.</p></li>
<li><p>Practical Implications: This MLE can be used as a baseline for predicting the expected number of reviews for similar listings under similar conditions. It also serves as a fundamental metric for comparison in more sophisticated models that might include additional variables such as price, location, or host response rates.</p></li>
</ul>
<p><br></p>
</section>
<section id="estimation-of-poisson-regression-model-for-airbnb-listings" class="level3">
<h3 class="anchored" data-anchor-id="estimation-of-poisson-regression-model-for-airbnb-listings">Estimation of Poisson Regression Model for Airbnb Listings</h3>
<p>Next, we extend our simple Poisson model to a Poisson Regression Model where the rate parameter (λ) is not constant but is a function of listing characteristics. This extension allows us to account for the variability in review counts due to factors such as room type, price, location, and host responsiveness.</p>
<p>To enhance the flexibility and accuracy of our model, I will include an additional argument to accommodate a covariate matrix, X. I will also adjust the model’s parameter from a single lambda to a vector of regression coefficients (beta). To ensure that lambda remains positive, as required, I’ll employ the exponential function as the inverse link function. Thus, we define lambda for each observation as exp(X’β), where X is the matrix of covariates, and β is the vector of coefficients. This modification allows us to model how multiple listing attributes influence the number of reviews, enhancing the robustness and relevance of our statistical analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Poisson regression log-likelihood function</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>poisson_regression_likelihood <span class="ot">&lt;-</span> <span class="cf">function</span>(beta, Y, X) {</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  lambda <span class="ot">&lt;-</span> <span class="fu">exp</span>(X <span class="sc">%*%</span> beta) </span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  log_likelihood <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fu">sum</span>(lambda) <span class="sc">+</span> <span class="fu">sum</span>(Y <span class="sc">*</span> <span class="fu">log</span>(lambda)) <span class="sc">-</span> <span class="fu">sum</span>(<span class="fu">lgamma</span>(Y <span class="sc">+</span> <span class="dv">1</span>))</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="sc">-</span>log_likelihood)  </span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="utilizing-the-poisson-regression-model-for-airbnb-reviews" class="level4">
<h4 class="anchored" data-anchor-id="utilizing-the-poisson-regression-model-for-airbnb-reviews">Utilizing the Poisson Regression Model for Airbnb Reviews</h4>
<p>I will now employ the updated likelihood or log-likelihood function that incorporates a covariate matrix, X, to perform parameter estimation using R’s optim() function. The matrix X will include a constant term and other relevant variables like room type, price, and additional listing features that might influence review counts.</p>
<p>After determining the maximum likelihood estimate (MLE) vector, I’ll use the Hessian matrix returned by the optimization function to calculate the standard errors of the beta parameter estimates. Finally, I will compile the results and present them in a table format, showcasing both the coefficients and their corresponding standard errors. This structured approach will provide a comprehensive statistical basis for our model, ensuring precise interpretation and robust decision-making.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>price <span class="ot">&lt;-</span> <span class="fu">scale</span>(airbnb<span class="sc">$</span>price)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>price_squared <span class="ot">&lt;-</span> airbnb<span class="sc">$</span>price<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>room_type <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(airbnb<span class="sc">$</span>room_type)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Model matrix</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(<span class="sc">~</span> room_type <span class="sc">+</span> price <span class="sc">+</span> <span class="fu">I</span>(price<span class="sc">^</span><span class="dv">2</span>), <span class="at">data =</span> airbnb)</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">&lt;-</span> airbnb<span class="sc">$</span>number_of_reviews  </span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Define a safe Poisson regression likelihood function</span></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>poisson_regression_likelihood <span class="ot">&lt;-</span> <span class="cf">function</span>(beta, Y, X) {</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>  eta <span class="ot">&lt;-</span> X <span class="sc">%*%</span> beta</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>  lambda <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">pmin</span>(eta, <span class="dv">20</span>))  </span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>  <span class="sc">-</span><span class="fu">sum</span>(<span class="fu">dpois</span>(Y, lambda, <span class="at">log =</span> <span class="cn">TRUE</span>))  </span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Initial beta estimates, possibly adjusted from zero if needed</span></span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a>initial_beta <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>, <span class="fu">ncol</span>(X))</span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Use 'optim' with a gradient method and provide the gradient if possible</span></span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">optim</span>(<span class="at">par =</span> initial_beta, <span class="at">fn =</span> poisson_regression_likelihood, <span class="at">Y =</span> Y, <span class="at">X =</span> X, <span class="at">method =</span> <span class="st">"BFGS"</span>, <span class="at">hessian =</span> <span class="cn">TRUE</span>)</span>
<span id="cb28-22"><a href="#cb28-22" aria-hidden="true" tabindex="-1"></a>beta_mle <span class="ot">&lt;-</span> result<span class="sc">$</span>par</span>
<span id="cb28-23"><a href="#cb28-23" aria-hidden="true" tabindex="-1"></a>hessian_matrix <span class="ot">&lt;-</span> result<span class="sc">$</span>hessian</span>
<span id="cb28-24"><a href="#cb28-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-25"><a href="#cb28-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the covariance matrix by inverting the Hessian</span></span>
<span id="cb28-26"><a href="#cb28-26" aria-hidden="true" tabindex="-1"></a>covariance_matrix <span class="ot">&lt;-</span> <span class="fu">solve</span>(hessian_matrix)</span>
<span id="cb28-27"><a href="#cb28-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-28"><a href="#cb28-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Standard errors are the square roots of the diagonal elements of the covariance matrix</span></span>
<span id="cb28-29"><a href="#cb28-29" aria-hidden="true" tabindex="-1"></a>std_errors <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">diag</span>(covariance_matrix))</span>
<span id="cb28-30"><a href="#cb28-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-31"><a href="#cb28-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a table of coefficients and their standard errors</span></span>
<span id="cb28-32"><a href="#cb28-32" aria-hidden="true" tabindex="-1"></a>coef_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Estimate =</span> beta_mle, <span class="at">Std_Error =</span> std_errors)</span>
<span id="cb28-33"><a href="#cb28-33" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(coef_table) <span class="ot">&lt;-</span> <span class="fu">colnames</span>(X)</span>
<span id="cb28-34"><a href="#cb28-34" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(coef_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          Estimate    Std_Error
(Intercept)            2.849234034 1.805864e-03
room_typePrivate room -0.158375396 2.811100e-03
room_typeShared room  -0.410233789 8.580588e-03
price                 -0.109143052 2.445932e-03
I(price^2)             0.001797472 4.938082e-05</code></pre>
</div>
</div>
</section>
<section id="interpretation-of-poisson-regression-coefficients-for-airbnb-listings" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-of-poisson-regression-coefficients-for-airbnb-listings">Interpretation of Poisson Regression Coefficients for Airbnb Listings</h4>
<ul>
<li><p>Intercept (Constant term): The estimate is 2.8492 with a standard error of 0.0018. The intercept represents the log count of reviews when all other covariates are zero, which in practical terms means a baseline number of reviews for the reference category of room types (likely Entire home/apt given typical data coding practices) and a price of zero. This high value suggests that, absent other influences, listings can expect an exponential number of reviews based on the exponent of this coefficient.</p></li>
<li><p>Room Type - Private Room: The coefficient for private rooms is -0.1584 with a standard error of 0.0028. This indicates that, holding other factors constant, private rooms are expected to have a lower log count of reviews compared to entire homes/apartments. This can be interpreted as private rooms being less likely to receive reviews relative to entire homes by a factor of exp(-0.1584), or about 85.35% of the review count of entire homes, all else being equal.</p></li>
<li><p>Room Type - Shared Room: The coefficient for shared rooms is -0.4102 with a standard error of 0.0086. This much more negative coefficient suggests a significantly lower log count of reviews compared to entire homes, with shared rooms getting only about 66.39% of the reviews of entire homes when other factors are held constant.</p></li>
<li><p>Price: The coefficient for price is -0.1091 with a standard error of 0.0024. This implies that as the price of a listing increases, the number of reviews tends to decrease. Specifically, each unit increase in price (which has been scaled) is associated with about 89.63% of the reviews compared to the baseline, holding other factors constant. This negative relationship indicates that higher-priced listings might deter reviews.</p></li>
<li><p>Price Squared (I(price^2)): The coefficient for the squared price term is 0.0018 with a standard error of 0.00005. The positive coefficient here indicates a curvilinear relationship between price and the number of reviews. As price increases, the initial deterrent effect on reviews (indicated by the negative linear term) starts to lessen, suggesting that at higher prices, the effect of price increases on deterring reviews diminishes.</p></li>
<li><p>Summary: The model suggests that room type and price significantly influence the number of reviews an Airbnb listing receives. While higher prices tend to decrease review counts, this effect is mitigated at higher price levels. Additionally, room type significantly impacts review frequency, with “Entire homes/apt” likely receiving more reviews compared to private and shared rooms. These findings can guide Airbnb hosts in pricing and room type decisions to optimize their visibility and attractiveness based on guest interaction through reviews.</p></li>
</ul>
</section>
</section>
</section>
<section id="modeling" class="level2">
<h2 class="anchored" data-anchor-id="modeling">Modeling</h2>
<p>Next, I will validate the estimates obtained from the custom optimization by using R’s glm() function to fit the same Poisson model with our covariate matrix X. This step will serve as a robustness check, allowing us to compare the results from our manual optimization approach to those derived from established GLM methods. This comparison helps ensure our model’s reliability and accuracy in predicting outcomes based on our data set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the Poisson regression model using glm() for the Airbnb dataset</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>price <span class="ot">&lt;-</span> <span class="fu">scale</span>(airbnb<span class="sc">$</span>price)  </span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>price_squared <span class="ot">&lt;-</span> airbnb<span class="sc">$</span>price<span class="sc">^</span><span class="dv">2</span>  </span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>room_type <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(airbnb<span class="sc">$</span>room_type)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the Poisson model</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>poisson_glm <span class="ot">&lt;-</span> <span class="fu">glm</span>(number_of_reviews <span class="sc">~</span> room_type <span class="sc">+</span> price <span class="sc">+</span> <span class="fu">I</span>(price<span class="sc">^</span><span class="dv">2</span>), <span class="at">family =</span> <span class="fu">poisson</span>(<span class="at">link =</span> <span class="st">"log"</span>), <span class="at">data =</span> airbnb)</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(poisson_glm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = number_of_reviews ~ room_type + price + I(price^2), 
    family = poisson(link = "log"), data = airbnb)

Coefficients:
                        Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)            2.8485154  0.0018112 1572.69   &lt;2e-16 ***
room_typePrivate room -0.1573724  0.0028419  -55.38   &lt;2e-16 ***
room_typeShared room  -0.4150007  0.0086168  -48.16   &lt;2e-16 ***
price                 -0.1090532  0.0026011  -41.93   &lt;2e-16 ***
I(price^2)             0.0019098  0.0000935   20.43   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 1340709  on 40627  degrees of freedom
Residual deviance: 1335518  on 40623  degrees of freedom
AIC: 1459572

Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
</section>
<section id="interpretation-of-poisson-regression-coefficients-for-airbnb-listings-1" class="level2">
<h2 class="anchored" data-anchor-id="interpretation-of-poisson-regression-coefficients-for-airbnb-listings-1">Interpretation of Poisson Regression Coefficients for Airbnb Listings</h2>
<section id="model-fit-and-coefficients" class="level3">
<h3 class="anchored" data-anchor-id="model-fit-and-coefficients">Model Fit and Coefficients:</h3>
<section id="intercept-entire-homeapt-at-base-price" class="level4">
<h4 class="anchored" data-anchor-id="intercept-entire-homeapt-at-base-price">Intercept (Entire Home/Apt at Base Price):</h4>
<ul>
<li>Estimate: 2.8485</li>
<li>Standard Error: 0.0018</li>
<li>Interpretation: The intercept represents the expected log count of reviews for “Entire home/apt” at the normalized base price (scaled to zero). This coefficient indicates a high baseline number of reviews for this category, suggesting that entire homes/apartments are generally well-received by guests.</li>
</ul>
</section>
<section id="room-type---private-room" class="level4">
<h4 class="anchored" data-anchor-id="room-type---private-room">Room Type - Private Room:</h4>
<ul>
<li>Coefficient: -0.1574</li>
<li>Standard Error: 0.0028</li>
<li>Interpretation: Relative to “Entire home/apt,” private rooms receive fewer reviews. The coefficient implies that private rooms receive exp(-0.1574), or about 85.44% of the reviews that entire homes/apartments receive, holding price constant.</li>
</ul>
</section>
<section id="room-type---shared-room" class="level4">
<h4 class="anchored" data-anchor-id="room-type---shared-room">Room Type - Shared Room:</h4>
<ul>
<li>Coefficient: -0.4150</li>
<li>Standard Error: 0.0086</li>
<li>Interpretation: Shared rooms receive significantly fewer reviews compared to entire homes/apartments, with a coefficient translating to about 66.02% of the reviews of entire homes/apartments, highlighting lower guest preference or satisfaction.</li>
</ul>
</section>
<section id="price" class="level4">
<h4 class="anchored" data-anchor-id="price">Price:</h4>
<ul>
<li>Coefficient: -0.1091</li>
<li>Standard Error: 0.0026</li>
<li>Interpretation: As price increases, the number of reviews decreases. Each unit increase in the scaled price leads to about 89.64% of the reviews compared to the lower price, indicating that higher prices might deter bookings or guest reviews.</li>
</ul>
</section>
<section id="price-squared-iprice2" class="level4">
<h4 class="anchored" data-anchor-id="price-squared-iprice2">Price Squared (I(price^2)):</h4>
<ul>
<li>Coefficient: 0.0019</li>
<li>Standard Error: 0.00009</li>
<li>Interpretation: The positive coefficient for price squared suggests diminishing negative impacts at higher prices, indicating a non-linear relationship where very high prices might not deter reviews as strongly, possibly due to luxury or unique offerings that attract a specific guest demographic.</li>
</ul>
</section>
<section id="model-diagnostics" class="level4">
<h4 class="anchored" data-anchor-id="model-diagnostics">Model Diagnostics:</h4>
<ul>
<li>Null and Residual Deviance: The significant drop in deviance when moving from the null model to the full model indicates a good fit of the model to the data.</li>
</ul>
</section>
<section id="strategic-implications-for-entering-airbnb-market" class="level4">
<h4 class="anchored" data-anchor-id="strategic-implications-for-entering-airbnb-market">Strategic Implications for Entering Airbnb Market:</h4>
<p>Given these findings, “Entire home/apt” priced below $2000 emerges as a highly attractive option for new hosts considering entering the Airbnb market:</p>
<ul>
<li>Optimal Price Range: Entire homes/apartments, particularly those priced below $2000, are likely to achieve high review scores and a higher number of reviews, making them appealing to potential guests.</li>
<li>Market Positioning: Focusing on this segment allows new hosts to capitalize on the high demand and positive guest perceptions associated with reasonably priced entire homes/apartments.</li>
<li>Revenue Optimization: Setting prices strategically within this range can maximize occupancy rates while maintaining high review scores, essential for growth and visibility on the platform.</li>
</ul>
</section>
<section id="conclusion" class="level4">
<h4 class="anchored" data-anchor-id="conclusion">Conclusion:</h4>
<p>The analysis strongly suggests that entering the Airbnb market with “Entire home/apt” offerings priced below $2000 provides a quantifiable benefit by aligning with guest preferences for value and quality. This segment offers a robust opportunity for new hosts to establish a successful presence on Airbnb.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    const typesetMath = (el) => {
      if (window.MathJax) {
        // MathJax Typeset
        window.MathJax.typeset([el]);
      } else if (window.katex) {
        // KaTeX Render
        var mathElements = el.getElementsByClassName("math");
        var macros = [];
        for (var i = 0; i < mathElements.length; i++) {
          var texText = mathElements[i].firstChild;
          if (mathElements[i].tagName == "SPAN") {
            window.katex.render(texText.data, mathElements[i], {
              displayMode: mathElements[i].classList.contains('display'),
              throwOnError: false,
              macros: macros,
              fleqn: false
            });
          }
        }
      }
    }
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        typesetMath(container);
        return container.innerHTML
      } else {
        typesetMath(note);
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      typesetMath(note);
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>